### ISSUE TITLE
Fix Travis build.

### ISSUE THREAD

**Issue by shurcooL** [sourcegraph/go-sourcegraph#80]
It looks like Travis is currently consistently failing. See, e.g., https://travis-ci.org/sourcegraph/go-sourcegraph/builds/86543608.

There are 2 versions of Go in the config, 1.4 and tip. 1.4 is passing, but tip is failing.

We should update 1.4 to 1.5, and either fix, or make tip an allowed failure.

**Comment by dmitshur** [comment]
This has been resolved via #89.

/cc @rothfels I now know you'll eventually find out about this (but not necessarily the second I write this comment). You'll also not get 2 separate emails because I'm making a comment _and_ closing the issue.

**Edit:** You'll also see this edit (along with other potential fixes), which wouldn't show up in email notifications.
